# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Just learning how to deploy a website using codecademy.com and Github. Nothing special to see/do here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
codecademy_username: musicknight
github_username:  suzzettemirunet

# Build settings
markdown: kramdown
